### ISSUE TITLE
can you provide a copy of Initial version ?

### ISSUE THREAD

**Issue by jackyliu16** [ruiyan-ma/ucb-61b-20sp#1]
Hello, I'm a student from another school, currently working on version 21 of the gitlet, but would like to know the difference between version 20 and 21 of the gitlet project, and would like to ask if you can provide the initial version of this 20sp project? 

I have tried some of this, but because my STFW ability is relatively weak, and a lot of 20, 21 content mixed together difficult to distinguish, so I want to consult you.

Finally, thank you very much

**Comment by ruiyan-ma** [comment]
Hi, I'm not sure about what the version 21 of gitlet project looks like, but I can tell you the initial skeleton code of version 20 is basically NOTHING. Only a Main.java file with an empty "public static void main" method inside it. Also, Makefile, UnitTest.java, Utils.java and all files in the testing folder are in the initial skeleton code. For version 20 they want you to do everything on your own, create everything you need and make the psvm method in Main.java work correctly. 

I finish this project in 2020 spring. At that time, although my code passed all tests on autograder, my code is a little bit messy and not well-structured. Recently I refactored most of the code in the gitlet project, also provide design doc for it. If you need help you can take a look at it. 

I think gitlet is a complex project and it's much more difficult than other projects in 61b (I've also done 61b 2018 spring and I think none of these projects can compare to gitlet). Gitlet forces you to thinking about how to organize your code and how to make your code work with each other in a clean and effective way. From my opinion it's more than just understanding and using data structures. 

Good luck!

**Comment by jackyliu16** [comment]
Thank you for your reply. I thought before that the 20-year version is similar to the 21 version, which provides a basic framework for everyone to develop on. I will carefully consider what you said in the later development process and read the design documents you provided.
best wises
